CMPUT301F24intels/intels-events

- gradle/libs.versions.toml
> Changed the gradle version

- app/build.gradle.kts
- app/src/main/java/com/example/intels_app/CaptureActivity.java
- app/src/main/java/com/example/intels_app/MainActivity.java
- app/src/main/java/com/example/intels_app/QRCodeScanner.java
- gradle/libs.versions.toml
added the functionality of qr code scanning.
> Added QrCodeScanner Class

- app/src/main/java/com/example/intels_app/MainActivity.java
- app/src/main/res/layout/waitlist_entrant.xml
> Fixed error in waitlist_entrant.xml and stopped QR camera from running when opening

- app/src/main/res/layout/admin_login.xml
- gradle/libs.versions.toml
Created the Admin Login page
Opened the UI on the app and it looks fine with all the editable fields being editable
> Jp admin login xml

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/MainActivity.java
- app/src/main/java/com/example/intels_app/QRCodeScanner.java
- app/src/main/java/com/example/intels_app/ScanQRActivity.java
- gradle/libs.versions.toml
Added ScanQRActivity class to handle the qr code scanning and redirecting to other pages.
> Implemented Join events functions

- app/src/main/java/com/example/intels_app/EventGridEntrantActivity.java
- app/src/main/java/com/example/intels_app/EventGridOrganizerActivity.java
- app/src/main/java/com/example/intels_app/MainActivity.java
> changed so view my waitlist first opens entrant view

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/CustomAdapterOrganizer.java
- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/Event.java
- app/src/main/java/com/example/intels_app/EventGridOrganizerActivity.java
> added entrantinwaitlist functionality when event is clicked from view my waitlist organizer POV

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/CustomAdapterManageEvents.java
- app/src/main/java/com/example/intels_app/Event.java
- app/src/main/java/com/example/intels_app/ManageEventsActivity.java
- app/src/main/res/layout/add_event.xml
> jp-newEvent

- app/src/main/java/com/example/intels_app/CustomAdapterFinalList.java
- app/src/main/java/com/example/intels_app/EventGridEntrantActivity.java
- app/src/main/java/com/example/intels_app/FinalList.java
- app/src/main/res/layout/final_list.xml
- app/src/main/res/layout/list_item_final.xml
- [x ] UI/UX improvement
- [x ] My code adheres to the coding and style guidelines of the project.
> made final list xml

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/CreateQR.java
- app/src/main/java/com/example/intels_app/Event.java
- app/src/main/java/com/example/intels_app/EventDetails.java
- app/src/main/java/com/example/intels_app/FirestoreData.java
- app/src/main/java/com/example/intels_app/ManageEventsActivity.java
- app/src/main/res/layout/event_details.xml
- app/src/main/res/layout/grid_item_manage_event.xml
- app/src/main/res/layout/manage_events.xml
- app/src/main/res/layout/qr_code_display.xml
> Jp generate qr

- app/src/main/java/com/example/intels_app/FirestoreData.java
- app/src/main/java/com/example/intels_app/ManageEventsActivity.java
> Jp Fix Bug

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/EditProfileActivity.java
- app/src/main/res/layout/edit_profile_page.xml
- [x ] New feature
- [x ] UI/UX improvement
> User can change profile pic using camera or from gallery

- .idea/deviceManager.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/AdminEvents.java
- app/src/main/java/com/example/intels_app/AdminLogin.java
- app/src/main/java/com/example/intels_app/AdminProfiles.java
- app/src/main/java/com/example/intels_app/EventGridOrganizerActivity.java
- app/src/main/res/layout/events_view.xml
- app/src/main/res/layout/profile_view.xml
- app/src/main/res/layout/sign_up.xml
- [x ] I have performed a self-review of my own code.
> Added profile view and events view to admind after logging in

- app/src/main/res/layout/join_waitlist.xml
- gradle/libs.versions.toml
> Added Join Waitlist xml and gradle version changed

- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/CreateQR.java
- app/src/main/java/com/example/intels_app/Event.java
- app/src/main/java/com/example/intels_app/ManageEventsActivity.java
> Fixing bug of event not creating

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/CreateQR.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
- app/src/main/java/com/example/intels_app/QRCodeScanner.java
- app/src/main/java/com/example/intels_app/SelectRoleActivity.java
- app/src/main/res/layout/join_waitlist.xml
- app/src/main/res/layout/select_role.xml
> Embedded Event details in Qr code

- app/src/main/java/com/example/intels_app/AdminProfiles.java
- app/src/main/java/com/example/intels_app/ManageEventsActivity.java
- app/src/main/java/com/example/intels_app/Profile.java
- app/src/main/res/layout/profile_view.xml
- gradle/libs.versions.toml
> Jp remove event

- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/res/layout/add_event.xml
- app/src/main/res/values/strings.xml
- gradle/libs.versions.toml
> Update to gradle files and fix add event xml

- app/src/main/java/com/example/intels_app/EventGridOrganizerActivity.java
- gradle/libs.versions.toml
> organizer updated event list from firestore

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/AdminEvents.java
- app/src/main/java/com/example/intels_app/AdminLogin.java
- app/src/main/java/com/example/intels_app/AdminProfiles.java
- app/src/main/java/com/example/intels_app/CreateFacility.java
- app/src/main/java/com/example/intels_app/EditProfileActivity.java
- app/src/main/java/com/example/intels_app/EventGridEntrantActivity.java
- app/src/main/java/com/example/intels_app/EventGridOrganizerActivity.java
- app/src/main/java/com/example/intels_app/Facility.java
- app/src/main/java/com/example/intels_app/MainActivity.java
- app/src/main/java/com/example/intels_app/MainPageActivity.java
- app/src/main/java/com/example/intels_app/ManageEventsActivity.java
- app/src/main/java/com/example/intels_app/ManageFacility.java
- app/src/main/java/com/example/intels_app/NotificationActivity.java
- app/src/main/java/com/example/intels_app/ScanQRActivity.java
- app/src/main/res/layout/create_facility.xml
- app/src/main/res/layout/event_details.xml
- app/src/main/res/layout/manage_events.xml
- app/src/main/res/layout/manage_facility.xml
- gradle/libs.versions.toml
> Prompt user to create facility if Device ID is not registered

- app/build.gradle.kts
- app/src/main/java/com/example/intels_app/CreateQR.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
- app/src/main/java/com/example/intels_app/QRCodeScanner.java
- app/src/main/res/layout/join_waitlist.xml
- gradle/libs.versions.toml
Modified the code to fetch the details from firestore
- [- ] Bug fix
> Poster image showing after scanning qr code

- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
- app/src/main/java/com/example/intels_app/NotificationActivity.java
- app/src/main/res/layout/event_details.xml
- app/src/main/res/layout/notification_item.xml
> Fixed the event details layout

- app/src/main/java/com/example/intels_app/AdminProfiles.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
- app/src/main/java/com/example/intels_app/Profile.java
- app/src/main/java/com/example/intels_app/ProfileAdapterAdmin.java
- app/src/main/java/com/example/intels_app/SignUp.java
> Jp delete profile

- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
- app/src/main/res/layout/waitlist_with_entrants.xml
> changed the layout of waitlist_with_entrant to address feedback

- app/src/main/java/com/example/intels_app/AdminProfiles.java
- app/src/main/java/com/example/intels_app/ProfileAdapterAdmin.java
> jp-deleteProfile

- .idea/deploymentTargetSelector.xml
- app/src/main/java/com/example/intels_app/DrawCompleteActivity.java
- app/src/main/java/com/example/intels_app/EntrantInCancelledWaitlist.java
- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/java/com/example/intels_app/FinalList.java
- app/src/main/java/com/example/intels_app/NotificationActivity.java
- app/src/main/res/layout/event_details.xml
- gradle/libs.versions.toml
> Updated the notification functionality and waitlist

- app/src/main/java/com/example/intels_app/CustomAdapterEntrant.java
- app/src/main/java/com/example/intels_app/EventGridEntrantActivity.java
- app/src/main/java/com/example/intels_app/EventGridOrganizerActivity.java
> view my waitlist for entrant shows the events they signed up for

- .idea/compiler.xml
- .idea/misc.xml
- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/EventGridEntrantActivity.java
- app/src/main/java/com/example/intels_app/EventGridOrganizerActivity.java
- app/src/main/java/com/example/intels_app/ManageEventsActivity.java
- gradle/libs.versions.toml
> Change Snapshot Listeners to OnComplete Listeners to prevent excessive FireBase reads

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/LotteryList.java
- app/src/main/res/layout/lottery_list.xml
> Added the lottery list layout and functionality

- app/src/main/java/com/example/intels_app/AdminProfiles.java
- app/src/main/res/layout/profile_view.xml
- app/src/main/res/menu/popup_menu.xml
- gradle/libs.versions.toml
> Remove facility added

- app/src/main/java/com/example/intels_app/CustomAdapterEntrant.java
- app/src/main/java/com/example/intels_app/CustomAdapterOrganizer.java
- app/src/main/java/com/example/intels_app/Entrant.java
- app/src/main/java/com/example/intels_app/EntrantAdapter.java
- app/src/main/java/com/example/intels_app/EntrantInCancelledWaitlist.java
- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
> adding javadocs to classes I created

- app/src/main/java/com/example/intels_app/ScanQRActivity.java
> Updated ScanQrActivity

- app/src/main/java/com/example/intels_app/ScanQRActivity.java
> Updated scanqr

- .idea/androidTestResultsUserPreferences.xml
- app/src/androidTest/java/com/example/intels_app/EventIntegrationTest.java
- app/src/androidTest/java/com/example/intels_app/NotificationsIntegrationTest.java
- app/src/androidTest/java/com/example/intels_app/WaitlistIntegrationTest.java
> refactoring to integration test

- .idea/other.xml
- app/src/main/java/com/example/intels_app/AdminProfiles.java
- gradle/libs.versions.toml
> remove Facility implemented in AdminProfiles

- app/src/main/java/com/example/intels_app/AdminProfiles.java
> Facility removal updated

- app/src/main/java/com/example/intels_app/EditProfileActivity.java
> Linked Edit profile with firestore

- .idea/compiler.xml
- .idea/gradle.xml
- .idea/misc.xml
- app/build.gradle.kts
> fixed issue

- app/src/main/java/com/example/intels_app/EntrantInCancelledWaitlist.java
- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/java/com/example/intels_app/FinalList.java
- app/src/main/java/com/example/intels_app/LotteryList.java
- app/src/main/java/com/example/intels_app/SelectedEntrantActivity.java
- app/src/main/java/com/example/intels_app/SelectedEntrantAdapter.java
- app/src/main/res/layout/lottery_list.xml
- app/src/main/res/layout/waitlist_with_entrants.xml
> Fixed the lottery functionality and selected entrants should now display the correct profile selected in the draw

- app/src/main/java/com/example/intels_app/EntrantInCancelledWaitlist.java
- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/NotificationActivity.java
- app/src/main/java/com/example/intels_app/ProfileAdapter.java
> The cancelled list should show now the entrant who declined to join the event

- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/FinalList.java
> Final list should show now the profile who accepted to join the event

- app/src/main/java/com/example/intels_app/CustomAdapterOrganizer.java
> Fixed CustomAdapterOrganizer.java

- app/src/main/java/com/example/intels_app/EntrantInCancelledWaitlist.java
> Fixed cancelledlist issue

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/CreateQR.java
- app/src/main/java/com/example/intels_app/CustomAdapterManageEvents.java
- app/src/main/java/com/example/intels_app/EditEventActivity.java
- app/src/main/java/com/example/intels_app/Event.java
- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/java/com/example/intels_app/ManageEventsActivity.java
- app/src/main/res/layout/add_event.xml
- app/src/main/res/layout/edit_event_details.xml
- app/src/main/res/layout/event_details.xml
- gradle/libs.versions.toml
> Jp update poster

- .idea/deploymentTargetSelector.xml
- .idea/gradle.xml
- .idea/misc.xml
- app/src/main/java/com/example/intels_app/FinalList.java
> Fixed finallist issue

- app/src/main/java/com/example/intels_app/CancelledProfileAdapter.java
- app/src/main/java/com/example/intels_app/EntrantInCancelledWaitlist.java
- app/src/main/java/com/example/intels_app/ProfileAdapter.java
> Added a delete button in each profile for cancelled entrants

- .idea/misc.xml
- app/src/main/java/com/example/intels_app/CancelledProfileAdapter.java
- app/src/main/java/com/example/intels_app/EntrantInCancelledWaitlist.java
> When delete button is click in cancelled list it'll delete the profile in firebase

- app/src/main/java/com/example/intels_app/EntrantInCancelledWaitlist.java
> Fixed the cancelled list custom notification to send in each profile

- .idea/misc.xml
- app/src/main/java/com/example/intels_app/EditProfileActivity.java
- app/src/main/java/com/example/intels_app/Profile.java
- app/src/main/java/com/example/intels_app/ProfileDetailsAdmin.java
- app/src/main/java/com/example/intels_app/SignUp.java
- app/src/main/res/layout/edit_profile_page.xml
- app/src/main/res/layout/profile_details_admin.xml
- app/src/main/res/layout/sign_up.xml
> Edit Profile Done: User can edit name , email, phone number, and profile picture and changes show up in database

- .idea/deploymentTargetSelector.xml
- app/src/main/java/com/example/intels_app/CustomAdapterManageEvents.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
…list that requires geolocation tracking.
> Warn users that their geolocation will be tracked if they join a waitlist that requires geolocation

- app/src/main/java/com/example/intels_app/CancelledProfileAdapter.java
- app/src/main/java/com/example/intels_app/CustomAdapterOrganizer.java
- app/src/main/java/com/example/intels_app/EditEventActivity.java
- app/src/main/java/com/example/intels_app/EventDetailsAdmin.java
- app/src/main/java/com/example/intels_app/FacilityDetailsAdmin.java
- app/src/main/java/com/example/intels_app/ProfileDetailsAdmin.java
> Add confirmation dialogs where applicable

- app/src/main/java/com/example/intels_app/FinalList.java
- app/src/main/res/layout/final_list.xml
- app/src/main/res/layout/waitlist_with_cancelled_entrants.xml
> Fixed cancelled list layout and final list

- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
- app/src/main/java/com/example/intels_app/Notification.java
- app/src/main/java/com/example/intels_app/NotificationActivity.java
> notifications based on deviceId should work now

- app/src/main/java/com/example/intels_app/AddEvent.java
> Event poster can be added via Camera

- app/src/main/java/com/example/intels_app/MainActivity.java
> Fix import error

- .idea/misc.xml
- app/src/main/java/com/example/intels_app/CustomAdapterEntrant.java
- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
- app/src/main/java/com/example/intels_app/LotteryList.java
> updated redraw functionality

- .idea/misc.xml
- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivity.java
> REDRAW WORKSSSSS

- .idea/misc.xml
- app/src/main/java/com/example/intels_app/ManageFacility.java
> Edit Profile and Manage Facility DONE!

- app/src/main/java/com/example/intels_app/Entrant.java
- app/src/main/java/com/example/intels_app/EntrantAdapter.java
- app/src/main/java/com/example/intels_app/EntrantInCancelledWaitlist.java
- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/LotteryList.java
- app/src/main/java/com/example/intels_app/Profile.java
- app/src/main/java/com/example/intels_app/ProfileAdapter.java
- app/src/main/java/com/example/intels_app/SelectedEntrantAdapter.java
> now lists show up with the profile pictures

- app/src/main/java/com/example/intels_app/SignUp.java
- app/src/main/res/layout/sign_up.xml
> Phone number optional

- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/CreateFacility.java
- app/src/main/java/com/example/intels_app/CustomAdapterManageEvents.java
- app/src/main/java/com/example/intels_app/EditEventActivity.java
- app/src/main/java/com/example/intels_app/Event.java
- app/src/main/java/com/example/intels_app/EventDetailsAdmin.java
- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/java/com/example/intels_app/FacilityDetailsAdmin.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivityTemp.java
- app/src/main/java/com/example/intels_app/ManageFacility.java
- app/src/main/java/com/example/intels_app/ProfileAdapterAdmin.java
- app/src/main/res/layout/add_event.xml
- app/src/main/res/layout/admin_event_details.xml
- app/src/main/res/layout/edit_event_details.xml
- app/src/main/res/layout/grid_item_entrant.xml
- app/src/main/res/layout/manage_facility.xml
> Jp fixing minor

- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/EditProfileActivity.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivityTemp.java
- app/src/main/java/com/example/intels_app/MainActivity.java
- app/src/main/java/com/example/intels_app/ManageFacility.java
- app/src/main/java/com/example/intels_app/QRCodeScanner.java
- app/src/main/java/com/example/intels_app/SignUp.java
> Camera is using webcam

- .idea/deploymentTargetSelector.xml
- app/src/main/java/com/example/intels_app/JoinWaitlistActivityTemp.java
> after updates and resolving errors from demo day

- .idea/deploymentTargetSelector.xml
- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/EditEventActivity.java
> Added date/time dialog when organizer wants to edit event info

- .idea/deploymentTargetSelector.xml
- app/src/main/java/com/example/intels_app/EntrantInWaitlist.java
- app/src/main/java/com/example/intels_app/EventDetailsOrganizer.java
- app/src/main/java/com/example/intels_app/JoinWaitlistActivityTemp.java
> all lists should work

- app/src/main/java/com/example/intels_app/DrawCompleteActivity.java
- app/src/main/res/layout/draw_complete.xml
> Added a background in the draw complete animation

- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/res/layout/draw_complete.xml
> Changed date/time format

- .idea/deploymentTargetSelector.xml
- app/src/main/res/layout/draw_complete.xml
> Fixed the draw complete layout

- app/src/main/java/com/example/intels_app/EditEventActivity.java
> Fixed the date/time format in edit event details

- app/src/main/java/com/example/intels_app/MapsActivity.java
- app/src/main/res/layout/activity_maps.xml
> added back button to maps activity

- .idea/gradle.xml
- app/src/main/java/com/example/intels_app/CustomAdapterManageEvents.java
- app/src/main/java/com/example/intels_app/CustomAdapterOrganizer.java
- app/src/main/java/com/example/intels_app/EventGridOrganizerActivity.java
- app/src/main/java/com/example/intels_app/ManageEventsActivity.java
- app/src/main/res/layout/grid_item_manage_event.xml
> Fix admin crashing

- .idea/deploymentTargetSelector.xml
> Deployment File changed automatically

- app/src/main/java/com/example/intels_app/AddEvent.java
- app/src/main/java/com/example/intels_app/AdminEvents.java
- app/src/main/java/com/example/intels_app/AdminFacilities.java
- app/src/main/java/com/example/intels_app/AdminLogin.java
- app/src/main/java/com/example/intels_app/AdminProfiles.java
- app/src/main/java/com/example/intels_app/CancelledProfileAdapter.java
- app/src/main/java/com/example/intels_app/CreateFacility.java
- app/src/main/java/com/example/intels_app/CreateQR.java
> Added method documentation until CreateQR

- .idea/misc.xml
- app/src/main/java/com/example/intels_app/JoinWaitlistActivityTemp.java
> limit entrants should properly work now

- .idea/misc.xml
> File changed when running

- app/src/main/java/com/example/intels_app/EditProfileActivity.java
- app/src/main/java/com/example/intels_app/SignUp.java
- app/src/main/res/layout/profilegrid.xml
- app/src/main/res/values/colors.xml
> Fixed the admin profile image cutout problem

- app/src/main/java/com/example/intels_app/MapsActivity.java
> DOES GEOLOCATION WORK NOW?
